INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (8, 8011366, '언론,미디어 > 방송 > 방송국', 'KBS 별관', 1, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (9, 8663561, '교육,학문 > 학교 > 대학교', '홍익대학교 서울캠퍼스', 1, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (10, 8234642, '여행 > 관광,명소 > 문화유적 > 문', '광화문', 1, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (11, 10305191, '여행 > 관광,명소 > 문화유적 > 고궁,궁', '덕수궁', 2, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (12, 10771162, '여행 > 관광,명소 > 문화유적 > 고궁,궁', '창덕궁', 2, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (13, 8625328, '여행 > 공원 > 도시근린공원', '탑골공원', 2, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (14, 23444676, '부동산 > 빌딩', '롯데월드타워', 3, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (15, 8829033, '가정,생활 > 장례 > 국립묘지', '국립서울현충원', 3, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (16, 11137036, '교육,학문 > 학교 > 대학교', '서울대학교 관악캠퍼스', 3, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (17, 26406915, '부동산 > 빌딩', '63스퀘어', 4, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (18, 7832114, '여행 > 공원 > 도시근린공원', '도산근린공원', 4, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (19, 8077761, '문화,예술 > 문화시설 > 기념관', '전쟁기념관', 4, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (20, 8246129, '여행 > 공원 > 도시근린공원', '남산공원', 5, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (21, 8023565, '여행 > 공원', '올림픽공원', 5, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (22, 1913983226, '여행 > 관광,명소', '남산서울타워', 5, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (23, 1873127229, '문화,예술 > 문화시설 > 박물관', '국립항공박물관', 6, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (24, 18742697, '사회,공공기관 > 입법기관', '국회의사당', 6, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (25, 12461589, '여행 > 관광,명소 > 섬 > 섬(내륙)', '월미도', 6, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (26, 7834307, '여행 > 관광,명소 > 문화유적 > 문', '독립문', 7, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (27, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 7, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (28, 8136085, '여행 > 공원 > 도시근린공원', '뚝섬한강공원', 7, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (29, 8052891, '의료,건강 > 병원 > 시도립병원', '인천광역시의료원', 8, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (30, 17384577, '여행 > 공원 > 도시근린공원', '자유공원', 8, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (31, 26563803, '여행 > 관광,명소 > 도보여행', '무의바다누리길', 8, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (32, 11377558, '의료,건강 > 병원 > 대학병원', '인하대병원', 9, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (33, 10560387, '문화,예술 > 문화시설 > 전시관', '송도컨벤시아', 9, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (34, 1149198308, '여행 > 관광,명소 > 군립공원', '고려천도공원', 9, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (35, 7836949, '여행 > 관광,명소 > 문화유적 > 유적지', '덕진진', 10, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (36, 8052890, '문화,예술 > 문화시설 > 박물관', '인천광역시립박물관', 10, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (37, 11320114, '여행 > 관광,명소 > 테마파크', '인천대공원', 10, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (38, 11340048, '문화,예술 > 문화시설 > 박물관', '부평역사박물관', 11, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (39, 27079251, '여행 > 관광,명소 > 전망대', '아라마루전망대', 11, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (40, 25609546, '여행 > 공원', '송도달빛축제공원', 11, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (41, 549627411, '문화,예술 > 도서 > 출판사', '원더박스', 12, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (42, 17384577, '여행 > 공원 > 도시근린공원', '자유공원', 12, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (43, 10145688, '문화,예술 > 문화시설 > 전시관', '국립생물자원관', 12, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (44, 7842981, '교통,수송 > 기차,철도 > 기차역 > KTX,SRT정차역', '동대구역', 13, 3);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (45, 8257954, '여행 > 관광,명소 > 섬 > 섬(내륙)', '동백섬', 13, 2);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (46, 8215041, '문화,예술 > 문화시설 > 박물관', '국립광주박물관', 13, 5);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (47, 8217829, '문화,예술 > 문화시설 > 과학관', '국립중앙과학관', 14, 6);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (48, 25049342, '문화,예술 > 문화시설 > 박물관', '울산박물관', 14, 7);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (49, 27538123, '여행 > 관광,명소 > 수목원,식물원', '국립세종수목원', 14, 8);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (50, 12027576, '문화,예술 > 문화시설 > 박물관', '수원화성박물관', 15, 9);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (51, 10158575, '여행 > 관광,명소 > 문화유적', '경포대', 15, 10);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (52, 945074967, '여행 > 관광,명소 > 전망대', '홍성스카이타워', 15, 12);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (53, 27603721, '여행 > 공원 > 도시근린공원', '전주덕진공원', 16, 13);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (54, 11739604, '문화,예술 > 문화시설 > 박물관', '목포근대역사관 1관', 16, 14);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (55, 19357172, '여행 > 관광,명소 > 테마거리', '성안길', 16, 15);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (56, 12819705, '교통,수송 > 도로시설 > 교량,다리', '월영교', 17, 16);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (57, 22018991, '여행 > 관광,명소 > 해수욕장,해변', '광암해수욕장', 17, 17);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (58, 15174204, '여행 > 관광,명소 > 산', '한라산', 17, 17);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (59, 8191467, '문화,예술 > 문화시설 > 박물관', '국립민속박물관', 18, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (60, 15153600, '교통,수송 > 도로시설 > 교량,다리 > 대교', '양화대교', 18, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (61, 11156260, '여행 > 관광,명소 > 문화유적 > 고궁,궁', '창경궁', 18, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (62, 10952963, '여행 > 공원 > 도시근린공원', '여의도한강공원', 19, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (63, 8430129, '사회,공공기관 > 지방행정기관 > 시청 > 특별시청', '서울특별시청', 19, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (64, 7945712, '여행 > 관광,명소 > 문화유적 > 탑,비석', '올림픽공원 세계평화의문', 19, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (65, 1269255937, '여행 > 공원', '가로공원', 20, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (66, 8830150, '문화,예술 > 문화시설 > 박물관', '국립중앙박물관', 20, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (67, 8142957, '여행 > 공원 > 도시근린공원', '반포한강공원', 20, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (68, 8252248, '여행 > 관광,명소 > 섬 > 섬(내륙)', '노들섬', 21, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (69, 7990409, '여행 > 관광,명소 > 테마거리', '압구정로데오거리', 21, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (70, 10305191, '여행 > 관광,명소 > 문화유적 > 고궁,궁', '덕수궁', 21, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (71, 27560699, '여행 > 관광,명소 > 테마파크', '롯데월드 어드벤처', 22, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (72, 9113903, '교통,수송 > 기차,철도 > 기차역 > KTX정차역', '서울역', 22, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (73, 7996800, '여행 > 관광,명소 > 테마파크', '서울어린이대공원 놀이동산', 22, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (74, 26970621, '교통,수송 > 교통시설 > 공항', '김포국제공항 국내선', 23, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (75, 18619553, '여행 > 관광,명소 > 문화유적 > 고궁,궁', '경복궁', 23, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (76, 11358098, '여행 > 공원 > 도시근린공원', '여의도공원', 23, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (77, 26537710, '문화,예술 > 문화시설 > 전시관', '월미문화관', 24, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (78, 10740434, '가정,생활 > 시장', '인천종합어시장', 24, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (79, 8395842, '여행 > 공원 > 도시근린공원', '수봉공원', 24, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (80, 10560387, '문화,예술 > 문화시설 > 전시관', '송도컨벤시아', 25, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (81, 12960848, '문화,예술 > 문화시설 > 박물관', '인천개항박물관', 25, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (82, 10663735, '교통,수송 > 교통시설 > 항구,포구 > 부두', '인천항 연안부두', 25, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (83, 26121040, '여행 > 관광,명소 > 유원지', '실미유원지', 26, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (84, 7999804, '여행 > 관광,명소 > 문화유적', '연미정', 26, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (85, 10757047, '문화,예술 > 문화시설 > 기념관', '인천상륙작전기념관', 26, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (86, 13121236, '부동산 > 빌딩', 'G타워', 27, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (87, 13582519, '여행 > 관광,명소 > 수목원,식물원', '인천수목원', 27, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (88, 8173287, '여행 > 관광,명소 > 문화유적 > 탑,비석', '부근리고인돌군', 27, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (89, 17103159, '부동산 > 지명', '경인아라뱃길 프로그램들판', 28, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (90, 10169429, '문화,예술 > 문화시설', '계양문화회관', 28, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (91, 215501965, '문화,예술 > 문화시설 > 박물관', '인천광역시역사자료관', 28, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (92, 17709537, '문화,예술 > 문화시설 > 박물관', '인천서구녹청자박물관', 29, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (93, 9320981, '여행 > 관광,명소 > 해수욕장,해변', '을왕리해수욕장', 29, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (94, 8638896, '여행 > 관광,명소 > 국립공원', '팔공산국립공원', 29, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (95, 8699685, '문화,예술 > 문화시설 > 박물관', '광주역사민속박물관', 30, 5);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (96, 8202423, '여행 > 관광,명소 > 해수욕장,해변', '광안리해수욕장', 30, 2);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (97, 17572778, '문화,예술 > 문화시설 > 박물관', '수원월드컵경기장 축구박물관', 30, 9);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (98, 703168965, '문화,예술 > 문화시설 > 아쿠아리움', '대전엑스포아쿠아리움', 31, 6);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (99, 25039682, '여행 > 관광,명소 > 국가정원', '태화강국가정원', 31, 7);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (100, 280876843, '여행 > 공원', '정부세종청사 옥상정원', 31, 8);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (101, 11164998, '여행 > 관광,명소 > 해수욕장,해변', '정동진해변', 32, 10);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (102, 10424223, '여행 > 관광,명소 > 문화유적', '문의문화재단지', 32, 11);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (103, 27526692, '교육,학문 > 교육단체 > 체험학습장', '상주시산림조합 백두대간 생태교육장', 32, 12);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (104, 21477292, '문화,예술 > 문화시설', '전주한벽문화관', 33, 13);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (105, 7876112, '문화,예술 > 문화시설 > 박물관', '목포자연사박물관', 33, 14);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (106, 26334065, '문화,예술 > 종교 > 불교 > 절,사찰', '법흥사', 33, 15);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (107, 8023584, '여행 > 공원 > 도시근린공원', '용지공원 용지호수공원', 34, 16);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (108, 11041974, '여행 > 관광,명소 > 해수욕장,해변', '검멀레해변', 34, 17);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (109, 12502196, '음식점 > 한식 > 국수', '옛날국수맛집', 34, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (110, 11232276, '음식점 > 양식', '터치더스카이', 35, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (111, 1512528379, '음식점 > 한식 > 육류,고기', '육성숙', 35, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (112, 2012513201, '음식점 > 한식 > 육류,고기 > 족발,보쌈', '정담은보쌈 북촌점', 35, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (113, 2143988257, '음식점 > 중식', '진중 우육면관', 36, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (114, 1255186883, '음식점 > 한식', '제주미향해장 명동본점', 36, 17);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (115, 615034120, '음식점 > 양식', '쌤쌤쌤 월드몰점', 36, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (116, 1420174243, '음식점 > 일식 > 돈까스,우동', '가츠가게', 37, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (117, 52853731, '음식점 > 샤브샤브', '샤브로21', 37, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (118, 2079352583, '음식점 > 양식', '디어앨리스', 37, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (119, 1487092810, '음식점 > 양식', '심퍼티쿠시 가로수길점', 38, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (120, 15659043, '음식점 > 분식', '현선이네 용산본점', 38, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (121, 1201214796, '음식점 > 한식 > 국수 > 칼국수', '함초밭들깨칼국수', 38, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (122, 43972424, '음식점 > 한식', '육첩반상 남산서울타워점', 39, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (123, 806395417, '음식점 > 한식', '서울로인 서울점', 39, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (124, 300278768, '음식점 > 한식 > 육류,고기 > 갈비', '마초갈비', 39, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (125, 281681269, '음식점 > 패밀리레스토랑 > 빕스', '빕스 어린이대공원점', 40, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (126, 16732242, '음식점 > 한식 > 찌개,전골', '한옥집김치찜 서대문본점', 40, 1);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (127, 14549731, '음식점 > 한식 > 해물,생선', '송쭈집 본점', 40, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (128, 1211271886, '음식점 > 한식 > 해물,생선 > 조개', '청춘조개 월미도직영점', 41, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (129, 1634966342, '음식점 > 한식 > 국수 > 칼국수', '97도씨 해물칼국수 영종본점', 41, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (130, 11169444, '음식점 > 한식 > 순대', '인하찹쌀순대', 41, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (131, 7828812, '음식점 > 중식 > 중국요리', '대창반점', 42, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (132, 1256147772, '음식점 > 한식 > 육류,고기', '신포동뒷고기', 42, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (133, 8246129, '여행 > 공원 > 도시근린공원', '남산공원', 42, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (134, 1539301950, '음식점 > 한식 > 육류,고기 > 삼겹살', '옥이이모네', 43, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (135, 573398466, '음식점 > 한식 > 해물,생선', '철주네생선구이', 43, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (136, 1558528456, '음식점 > 한식', '그리울 평화전망대점', 43, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (137, 753259454, '음식점 > 한식 > 해물,생선', '신복관 송도센트럴파크점', 44, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (138, 65983946, '음식점 > 일식 > 일식집', '긴자 송도유원지점', 44, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (139, 2068653615, '음식점 > 카페 > 테마카페 > 디저트카페', '망원동티라미수 송도달빛축제공원역점', 44, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (140, 819616502, '음식점 > 샤브샤브', '광성보한식샤브샤브', 45, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (141, 1268036958, '음식점 > 일식 > 돈까스,우동', '은식당 검암점', 45, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (142, 1493560379, '음식점 > 퓨전요리', '정정아식당앤포차', 45, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (143, 26646634, '음식점 > 중식 > 중국요리', '럭키차이나', 46, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (144, 244723494, '음식점 > 한식', '준서네 돌담집', 46, 2);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (145, 9597693, '음식점 > 한식 > 육류,고기 > 오리', '팔공산이재욱호박오리', 46, 3);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (146, 455501700, '음식점 > 한식 > 국밥', '오복돼지국밥', 47, 5);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (147, 7960840, '음식점 > 한식 > 육류,고기 > 갈비', '송정떡갈비 1호점', 47, 6);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (148, 1181429503, '음식점 > 일식 > 초밥,롤', '시바스시', 47, 7);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (149, 1650426886, '교통,수송 > 교통시설 > 주차장', '태평소국밥 본점 주차장', 48, 8);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (150, 373629696, '음식점 > 중식 > 중국요리', '마라공방 세종점', 48, 9);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (151, 1565753128, '음식점 > 퓨전요리', '미식가의주방', 48, 10);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (152, 2069120916, '음식점 > 한식 > 육류,고기 > 닭요리', '함가네닭갈비', 49, 11);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (153, 11891832, '음식점 > 한식 > 육류,고기', '내당한우', 49, 12);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (154, 1703173003, '음식점 > 한식 > 해물,생선', '신안선도뻘낙지', 49, 13);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (155, 26615208, '음식점 > 한식 > 국밥', '전주왱이콩나물국밥전문점', 50, 14);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (156, 7881188, '음식점 > 한식 > 육류,고기 > 닭요리', '밀레니엄안동찜닭', 50, 15);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (157, 1860433447, '음식점 > 한식 > 육류,고기', '돌담흑돼지 중문', 50, 16);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (158, 12461589, '여행 > 관광,명소 > 섬 > 섬(내륙)', '월미도', 51, 17);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (159, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 51, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (160, 8830150, '문화,예술 > 문화시설 > 박물관', '국립중앙박물관', 51, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (161, 10757047, '문화,예술 > 문화시설 > 기념관', '인천상륙작전기념관', 52, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (162, 25609546, '여행 > 공원', '송도달빛축제공원', 52, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (163, 8059361, '음식점 > 한식 > 국밥', '임진각식당', 52, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (164, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 53, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (165, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 53, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (166, 8830150, '문화,예술 > 문화시설 > 박물관', '국립중앙박물관', 53, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (167, 10757047, '문화,예술 > 문화시설 > 기념관', '인천상륙작전기념관', 54, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (168, 25609546, '여행 > 공원', '송도달빛축제공원', 54, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (169, 8059361, '음식점 > 한식 > 국밥', '임진각식당', 54, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (170, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 55, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (171, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 55, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (172, 10751028, '교통,수송 > 교통시설 > 공항', '인천국제공항', 53, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (173, 8189016, '음식점 > 중식 > 중국요리', '공화춘 차이나타운1호점', null, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (174, 1774221513, '교통,수송 > 교통시설 > 주차장 > 공영주차장', '동화마을 공영주차장', null, 4);
INSERT INTO goat.place (place_num, api_id, category_name, place_name, blog_num, cno) VALUES (175, 1745042389, '음식점 > 한식 > 해물,생선 > 조개', '월미루프탑24시', null, 4);
